# Generated by Django 3.0 on 2020-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200615_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.idfood.co.uk/wp-content/plugins/woocommerce/assets/images/placeholder.png,null=True', max_length=500),
        ),
    ]
